github.com:
    users:
        Jaetan:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: Jaetan
