#!/home/nicolas/.local/bin/python3.14
"""Replay real Bash calls from past session transcripts through both live hooks; write every answer to a JSON file.

usage: replay_corpus.py extract <corpus.json>
       replay_corpus.py run <corpus.json> <label> [HOOKS_DIR]   -> results-<label>.json beside the corpus
       replay_corpus.py diff <results-a.json> <results-b.json>

Every hook child runs under RLIMIT_AS = CAP and a timeout, so a runaway reading is a MemoryError, never a host OOM.
Each call gets its own session id and the state directory is a fresh one per label, so answers do not depend on
the order of the calls. The corpus (every distinct Bash call in ~/.claude/projects, about 20 MB) is regenerated by
`extract`; run `run` before and after a change to the hooks, then `diff`.
"""
import concurrent.futures as cf
import glob
import json
import os
import resource
import shutil
import subprocess
import sys
from pathlib import Path

HOOKS = str(Path(__file__).resolve().parent.parent)  # the hooks this tests/ directory belongs to
PROJECTS = "/home/nicolas/.claude/projects"
CAP = 1 << 30
WORKERS = 6
HOOK_NAMES = ("heavy-run-guard.py", "no-polling-loops.py")


def extract(out: Path) -> None:
    seen: dict[str, str] = {}
    files = sorted(glob.glob(f"{PROJECTS}/*/*.jsonl"), key=os.path.getmtime)
    for f in files:
        with open(f, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                if '"tool_use"' not in line:
                    continue
                try:
                    d = json.loads(line)
                except ValueError:
                    continue
                c = d.get("message", {}).get("content") if isinstance(d.get("message"), dict) else None
                if not isinstance(c, list):
                    continue
                for x in c:
                    if x.get("type") == "tool_use" and x.get("name") == "Bash":
                        cmd = (x.get("input") or {}).get("command")
                        if isinstance(cmd, str) and cmd.strip() and cmd not in seen:
                            seen[cmd] = d.get("cwd") or "/home/nicolas/dev/agda/aletheia"
    corpus = [{"command": k, "cwd": v} for k, v in seen.items()]
    out.write_text(json.dumps(corpus))
    print(f"{len(corpus)} distinct calls from {len(files)} transcripts")


def limit() -> None:
    resource.setrlimit(resource.RLIMIT_AS, (CAP, CAP))


def one(i: int, item: dict, hook: str, tmp: str, hooks: str) -> dict:
    event = {"hook_event_name": "PreToolUse", "tool_name": "Bash", "session_id": f"replay-{i}",
             "cwd": item["cwd"], "tool_input": {"command": item["command"]}}
    env = dict(os.environ, TMPDIR=tmp)
    try:
        p = subprocess.run([f"{hooks}/{hook}"], input=json.dumps(event), capture_output=True, text=True,
                           preexec_fn=limit, timeout=60, check=False, env=env)
        return {"i": i, "hook": hook, "rc": p.returncode, "out": p.stdout, "err": p.stderr}
    except subprocess.TimeoutExpired:
        return {"i": i, "hook": hook, "rc": None, "out": "", "err": "TIMEOUT"}


def run(corpus_path: Path, label: str, hooks: str) -> None:
    corpus = json.loads(corpus_path.read_text())
    tmp = corpus_path.parent / f"state-{label}"
    shutil.rmtree(tmp, ignore_errors=True)
    tmp.mkdir()
    results = []
    with cf.ThreadPoolExecutor(WORKERS) as ex:
        futs = [ex.submit(one, i, item, hook, str(tmp), hooks) for i, item in enumerate(corpus) for hook in HOOK_NAMES]
        for f in cf.as_completed(futs):
            results.append(f.result())
    results.sort(key=lambda r: (r["i"], r["hook"]))
    out = corpus_path.parent / f"results-{label}.json"
    out.write_text(json.dumps(results))
    mem = [r for r in results if "MemoryError" in r["err"]]
    tout = [r for r in results if r["rc"] is None]
    print(f"{len(results)} answers; MemoryError {len(mem)}; timeout {len(tout)}; "
          f"rc counts {dict(sorted({str(r['rc']): sum(1 for q in results if q['rc'] == r['rc']) for r in results}.items()))}")
    for r in mem + tout:
        print(f"  {r['hook']} #{r['i']}: {corpus[r['i']]['command'][:150]!r}")


def diff(a_path: Path, b_path: Path) -> int:
    a = {(r["i"], r["hook"]): r for r in json.loads(a_path.read_text())}
    b = {(r["i"], r["hook"]): r for r in json.loads(b_path.read_text())}
    corpus = json.loads((a_path.parent / "corpus.json").read_text())
    bad = 0
    for k in sorted(a):
        if (a[k]["rc"], a[k]["out"], a[k]["err"]) != (b[k]["rc"], b[k]["out"], b[k]["err"]):
            bad += 1
            print(f"DIFF {k[1]} #{k[0]} rc {a[k]['rc']} -> {b[k]['rc']}: {corpus[k[0]]['command'][:150]!r}")
            print(f"   before: {a[k]['err'][-300:]!r}")
            print(f"   after:  {b[k]['err'][-300:]!r}")
    print(f"{len(a)} answers compared, {bad} differ")
    return 1 if bad else 0


if __name__ == "__main__":
    mode = sys.argv[1]
    if mode == "extract":
        extract(Path(sys.argv[2]))
    elif mode == "run":
        run(Path(sys.argv[2]), sys.argv[3], sys.argv[4] if len(sys.argv) > 4 else HOOKS)
    else:
        sys.exit(diff(Path(sys.argv[2]), Path(sys.argv[3])))
