console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#414868'
  blue = '#7AA2F7'
  cyan = '#7DCFFF'
  green = '#73DACA'
  magenta = '#BB9AF7'
  red = '#F7768E'
  white = '#C0CAF5'
  yellow = '#E0AF68'

[secondary_prompt]
  template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
  foreground = 'p:black'
  background = 'transparent'

[transient_prompt]
  template = ' '
  foreground = 'p:blue'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = '╭─'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '
    foreground = 'p:black'
    background = 'p:white'
    type = 'os'

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{ path .Path .Location }} '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:green'
    type = 'path'

    [blocks.segments.properties]
      home_icon = '~'
      style = 'full'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:green'
    type = 'git'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#c4a000{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#89d1dc{{ end }}', '{{ if gt .Behind 0 }}#4e9a06{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      branch_max_length = 25
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}  '
    foreground = 'p:white'
    powerline_symbol = ''
    background = 'p:yellow'
    type = 'node'
    invert_powerline = true

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = 'p:blue'
    powerline_symbol = ''
    background = 'transparent'
    type = 'go'
    invert_powerline = true

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:blue'
    type = 'julia'
    invert_powerline = true

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:yellow'
    type = 'python'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_virtual_env = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:red'
    type = 'ruby'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:yellow'
    type = 'azfunc'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }}  '
    foreground = 'p:white'
    powerline_symbol = ''
    type = 'aws'
    background_templates = ['{{if contains "default" .Profile}}#FFA400{{end}}', '{{if contains "jan" .Profile}}#f1184c{{end}}']
    invert_powerline = true

    [blocks.segments.properties]
      display_default = false

  [[blocks.segments]]
    style = 'powerline'
    template = '  '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:yellow'
    type = 'root'
    invert_powerline = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .FormattedMs }}  '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:yellow'
    type = 'executiontime'
    invert_powerline = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if gt .Code 0 }}{{ reason .Code }}{{ else }}{{ end }} '
    foreground = 'p:white'
    powerline_symbol = ''
    background = 'p:black'
    type = 'status'
    background_templates = ['{{ if gt .Code 0 }}#cc2222{{ end }}']
    invert_powerline = true

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    style = 'diamond'
    trailing_diamond = '─╮'
    template = ' {{ .CurrentDate | date .Format }}  '
    foreground = 'p:black'
    background = 'p:white'
    type = 'time'
    invert_powerline = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '╰─'
    foreground = 'p:white'
    type = 'text'

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    style = 'plain'
    template = '─╯'
    foreground = 'p:white'
    type = 'text'
